"""Initial migration

Revision ID: 965b9e3a66a5
Revises: 
Create Date: 2026-02-14 15:59:25.534762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965b9e3a66a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('coach_token', sa.String(), nullable=True),
    sa.Column('match_status', sa.Enum('setup', 'live', 'expired', 'archived', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_rooms_expires_at'), 'rooms', ['expires_at'], unique=False)
    op.create_index(op.f('ix_rooms_slug'), 'rooms', ['slug'], unique=True)
    op.create_table('snapshots',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('full_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('side', sa.Enum('home', 'away', name='teamside'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_goalkeeper', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('teams')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_rooms_slug'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_expires_at'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
